import React from 'react';
import { ShotcraftPresetMeta, ShotcraftPresetId } from './types';

// Camera (2)
import { Basic3DScenePreset, BASIC_3D_SCENE_DURATION } from './shots/camera/Basic3DScenePreset';
import { CursorFlyoverPreset, CURSOR_FLYOVER_DURATION } from './shots/camera/CursorFlyoverPreset';

// Typography (11)
import { BlurSlidePreset, BLUR_SLIDE_DURATION } from './shots/typography/BlurSlidePreset';
import { BraceExpandPreset, BRACE_EXPAND_DURATION } from './shots/typography/BraceExpandPreset';
import { CelFlashStompPreset, CEL_FLASH_STOMP_DURATION } from './shots/typography/CelFlashStompPreset';
import { CountdownArcScatterPreset, COUNTDOWN_ARC_SCATTER_DURATION } from './shots/typography/CountdownArcScatterPreset';
import { GlitchCyclePreset, GLITCH_CYCLE_DURATION } from './shots/typography/GlitchCyclePreset';
import { PaperTitleCardPreset, PAPER_TITLE_CARD_DURATION } from './shots/typography/PaperTitleCardPreset';
import { TextAsMaskPreset, TEXT_AS_MASK_DURATION } from './shots/typography/TextAsMaskPreset';
import { TitleDemoteToLabelPreset, TITLE_DEMOTE_TO_LABEL_DURATION } from './shots/typography/TitleDemoteToLabelPreset';
import { SplitTextStaggerPreset, SPLIT_TEXT_STAGGER_DURATION } from './shots/typography/SplitTextStaggerPreset';
import { ScrambleDecodePreset, SCRAMBLE_DECODE_DURATION } from './shots/typography/ScrambleDecodePreset';
import { WordRelayFilmstripPreset, WORD_RELAY_FILMSTRIP_DURATION } from './shots/typography/WordRelayFilmstripPreset';

// Data (4)
import { CounterConfettiPreset, COUNTER_CONFETTI_DURATION } from './shots/data/CounterConfettiPreset';
import { RingDiagramAnnotationRevealPreset, RING_DIAGRAM_ANNOTATION_REVEAL_DURATION } from './shots/data/RingDiagramAnnotationRevealPreset';
import { TimelineTravelPreset, TIMELINE_TRAVEL_DURATION } from './shots/data/TimelineTravelPreset';
import { ValueStaggerGradientPreset, VALUE_STAGGER_GRADIENT_DURATION } from './shots/data/ValueStaggerGradientPreset';

// Effects & Metaphors (13)
import { BeatStepListThemeCyclePreset, BEAT_STEP_LIST_THEME_CYCLE_DURATION } from './shots/effects/BeatStepListThemeCyclePreset';
import { BezierSourceConvergeMergePreset, BEZIER_SOURCE_CONVERGE_MERGE_DURATION } from './shots/effects/BezierSourceConvergeMergePreset';
import { PanelToCanvasPreset, PANEL_TO_CANVAS_DURATION } from './shots/effects/PanelToCanvasPreset';
import { CardStackPreset, CARD_STACK_DURATION } from './shots/effects/CardStackPreset';
import { PopBurstConfirmPreset, POP_BURST_CONFIRM_DURATION } from './shots/effects/PopBurstConfirmPreset';
import { ListRevealPreset, LIST_REVEAL_DURATION } from './shots/effects/ListRevealPreset';
import { ProductCardProgressiveAssemblePreset, PRODUCT_CARD_PROGRESSIVE_ASSEMBLE_DURATION } from './shots/effects/ProductCardProgressiveAssemblePreset';
import { RadialRipplePhoneChipsPreset, RADIAL_RIPPLE_PHONE_CHIPS_DURATION } from './shots/effects/RadialRipplePhoneChipsPreset';
import { ResearchCardStackScrollPreset, RESEARCH_CARD_STACK_SCROLL_DURATION } from './shots/effects/ResearchCardStackScrollPreset';
import { SegmentedThumbHeroPreset, SEGMENTED_THUMB_HERO_DURATION } from './shots/effects/SegmentedThumbHeroPreset';
import { SkeletonRevealPreset, SKELETON_REVEAL_DURATION } from './shots/effects/SkeletonRevealPreset';
import { SvgShapeMorphPreset, SVG_SHAPE_MORPH_DURATION } from './shots/effects/SvgShapeMorphPreset';
import { IconFlipBloomPreset, ICON_FLIP_BLOOM_DURATION } from './shots/effects/IconFlipBloomPreset';

// Transition (1)
import { BottomPushStackWipePreset, BOTTOM_PUSH_STACK_WIPE_DURATION } from './shots/transition/BottomPushStackWipePreset';

export * from './types';
export * from './motionUtils';

// Export all components individually
export {
  Basic3DScenePreset,
  CursorFlyoverPreset,
  BlurSlidePreset,
  BraceExpandPreset,
  CelFlashStompPreset,
  CountdownArcScatterPreset,
  GlitchCyclePreset,
  PaperTitleCardPreset,
  TextAsMaskPreset,
  TitleDemoteToLabelPreset,
  SplitTextStaggerPreset,
  ScrambleDecodePreset,
  WordRelayFilmstripPreset,
  CounterConfettiPreset,
  RingDiagramAnnotationRevealPreset,
  TimelineTravelPreset,
  ValueStaggerGradientPreset,
  BeatStepListThemeCyclePreset,
  BezierSourceConvergeMergePreset,
  PanelToCanvasPreset,
  CardStackPreset,
  PopBurstConfirmPreset,
  ListRevealPreset,
  ProductCardProgressiveAssemblePreset,
  RadialRipplePhoneChipsPreset,
  ResearchCardStackScrollPreset,
  SegmentedThumbHeroPreset,
  SkeletonRevealPreset,
  SvgShapeMorphPreset,
  IconFlipBloomPreset,
  BottomPushStackWipePreset,
};

/**
 * Catálogo Oficial dos 31 Presets do Video-Shotcraft V1 adaptados ao OFurry Motion Engine
 */
export const SHOTCRAFT_V1_PRESETS: ShotcraftPresetMeta[] = [
  {
    id: 'basic-3d-scene',
    name: 'Basic 3D Scene',
    category: 'camera',
    defaultDurationInFrames: BASIC_3D_SCENE_DURATION,
    videoPreview: 'presets/videos/basic-3d-scene.mp4',
    recipeSource: 'camera/basic-3d-scene.md',
    ofurryArchetype: 'A (Blueprint / Ficha)',
    intention: 'Câmera 2.5D viajando entre cartões de premissa e armadilha no espaço vazio',
    description: 'Voo de câmera em perspectiva com parada em 4 etapas contratuais.',
    component: Basic3DScenePreset as unknown as React.FC<Record<string, unknown>>,
  },
  {
    id: 'cursor-flyover',
    name: 'Cursor Flyover',
    category: 'camera',
    defaultDurationInFrames: CURSOR_FLYOVER_DURATION,
    videoPreview: 'presets/videos/cursor-flyover.mp4',
    recipeSource: 'camera/cursor-flyover.md',
    ofurryArchetype: 'A (Blueprint / Ficha)',
    intention: 'Auditoria de 4 quadrantes de contrato com cursor neon e zoom-in 2.5D',
    description: 'Câmera rasante com cursor neon inspecionando cláusulas e gerando ripples de alerta.',
    component: CursorFlyoverPreset as unknown as React.FC<Record<string, unknown>>,
  },
  {
    id: 'blur-slide',
    name: 'Blur Slide Stagger',
    category: 'typography',
    defaultDurationInFrames: BLUR_SLIDE_DURATION,
    videoPreview: 'presets/videos/blur-slide.mp4',
    recipeSource: 'typography/blur-slide.md',
    ofurryArchetype: 'C (Crash Slam)',
    intention: 'Revelação ultra-suave com desfoque e subida sincronizada de palavras monumentais',
    description: 'Entrada de 1 a 3 palavras massivas com blur progressivo e micro-label superior.',
    component: BlurSlidePreset as unknown as React.FC<Record<string, unknown>>,
  },
  {
    id: 'brace-expand',
    name: 'Brace Expand Reveal',
    category: 'typography',
    defaultDurationInFrames: BRACE_EXPAND_DURATION,
    videoPreview: 'presets/videos/brace-expand.mp4',
    recipeSource: 'typography/brace-expand.md',
    ofurryArchetype: 'C (Crash Slam)',
    intention: 'Chaves neon monumentais se abrem em cortina revelando o termo central',
    description: 'Par de chaves {} com spring outBack revelando palavra-chave como cortina mecânica.',
    component: BraceExpandPreset as unknown as React.FC<Record<string, unknown>>,
  },
  {
    id: 'cel-flash-stomp',
    name: 'Cel Flash Stomp',
    category: 'typography',
    defaultDurationInFrames: CEL_FLASH_STOMP_DURATION,
    videoPreview: 'presets/videos/cel-flash-stomp.mp4',
    recipeSource: 'typography/cel-flash-stomp.md',
    ofurryArchetype: 'C (Crash Slam)',
    intention: 'Palavras de soco carimbadas com rotação sutil e background flash neon sólido',
    description: 'Impacto brutal de 3 palavras em sequência rápida com flashes de contraste no fundo.',
    component: CelFlashStompPreset as unknown as React.FC<Record<string, unknown>>,
  },
  {
    id: 'countdown-arc-scatter',
    name: 'Countdown Arc Scatter',
    category: 'typography',
    defaultDurationInFrames: COUNTDOWN_ARC_SCATTER_DURATION,
    videoPreview: 'presets/videos/countdown-arc-scatter.mp4',
    recipeSource: 'typography/countdown-arc-scatter.md',
    ofurryArchetype: 'B (Layered Stash)',
    intention: 'Varredura de números em arco polar desacelerando e cravando a métrica hero',
    description: 'Mostrador circular em arco que freia bruscamente no número alvo (ex: 5 anos).',
    component: CountdownArcScatterPreset as unknown as React.FC<Record<string, unknown>>,
  },
  {
    id: 'glitch-cycle',
    name: 'Glitch Cycle Decode',
    category: 'typography',
    defaultDurationInFrames: GLITCH_CYCLE_DURATION,
    videoPreview: 'presets/videos/glitch-cycle.mp4',
    recipeSource: 'typography/glitch-cycle.md',
    ofurryArchetype: 'C (Crash Slam)',
    intention: 'Ciclo de glitches denunciando a ilusão de promessas até cravar a realidade',
    description: 'Transição rápida com aberração cromática neon entre 4 frases de desmascaramento.',
    component: GlitchCyclePreset as unknown as React.FC<Record<string, unknown>>,
  },
  {
    id: 'paper-title-card',
    name: 'Paper Title Card',
    category: 'typography',
    defaultDurationInFrames: PAPER_TITLE_CARD_DURATION,
    videoPreview: 'presets/videos/paper-title-card.mp4',
    recipeSource: 'typography/paper-title-card.md',
    ofurryArchetype: 'A (Blueprint / Ficha)',
    intention: 'Cartão de título com impressão tipográfica letterpress e grifo neon sólido',
    description: 'Carimbo editorial com destaque em cor neon e linha de sublinhado cinematográfica.',
    component: PaperTitleCardPreset as unknown as React.FC<Record<string, unknown>>,
  },
  {
    id: 'text-as-mask',
    name: 'Text As Mask Zoom-Through',
    category: 'typography',
    defaultDurationInFrames: TEXT_AS_MASK_DURATION,
    videoPreview: 'presets/videos/text-as-mask.mp4',
    recipeSource: 'opening/text-as-mask.md',
    ofurryArchetype: 'C (Crash Slam)',
    intention: 'Tipografia massiva recortada como máscara com zoom 2.5D atravessando a letra',
    description: 'Palavra monumental (ex: ARMADILHA) contendo gradiente neon e mergulho de câmera.',
    component: TextAsMaskPreset as unknown as React.FC<Record<string, unknown>>,
  },
  {
    id: 'title-demote-to-label',
    name: 'Title Demote to Label',
    category: 'typography',
    defaultDurationInFrames: TITLE_DEMOTE_TO_LABEL_DURATION,
    videoPreview: 'presets/videos/title-demote-to-label.mp4',
    recipeSource: 'typography/title-demote-to-label.md',
    ofurryArchetype: 'B (Layered Stash)',
    intention: 'Título hero encolhe e vira micro-tag superior enquanto a métrica massiva sobe',
    description: 'Transição de hierarquia onde o conceito migra para a tag e a métrica 240px assume o palco.',
    component: TitleDemoteToLabelPreset as unknown as React.FC<Record<string, unknown>>,
  },
  {
    id: 'split-text-stagger',
    name: 'Split Text Stagger',
    category: 'typography',
    defaultDurationInFrames: SPLIT_TEXT_STAGGER_DURATION,
    videoPreview: 'presets/videos/split-text-stagger.mp4',
    recipeSource: 'typography/type-assembly-moves.md',
    ofurryArchetype: 'C (Crash Slam)',
    intention: 'Mask reveal da linha de base por caractere individual com hairline neon',
    description: 'Subida mecânica com overshoot calibrado de cada letra de 130px saindo do chão.',
    component: SplitTextStaggerPreset as unknown as React.FC<Record<string, unknown>>,
  },
  {
    id: 'scramble-decode',
    name: 'Scramble Cypher Decode',
    category: 'typography',
    defaultDurationInFrames: SCRAMBLE_DECODE_DURATION,
    videoPreview: 'presets/videos/scramble-decode.mp4',
    recipeSource: 'typography/type-entrance-moves.md',
    ofurryArchetype: 'A (Blueprint / Ficha)',
    intention: 'Decodificador alfanumérico rápido travando caractere por caractere com flash',
    description: 'Sequência terminal hacker que trava na taxa oculta revelada.',
    component: ScrambleDecodePreset as unknown as React.FC<Record<string, unknown>>,
  },
  {
    id: 'word-relay-filmstrip',
    name: 'Word Relay Filmstrip',
    category: 'typography',
    defaultDurationInFrames: WORD_RELAY_FILMSTRIP_DURATION,
    videoPreview: 'presets/videos/word-relay-filmstrip.mp4',
    recipeSource: 'typography/word-relay-filmstrip.md',
    ofurryArchetype: 'D (Split Tensão)',
    intention: 'Divisão 50/50 com sujeito estático à esquerda e carretel de verbos à direita',
    description: 'Rolagem vertical precisa de ações mecânicas com destaque em neon laranja.',
    component: WordRelayFilmstripPreset as unknown as React.FC<Record<string, unknown>>,
  },
  {
    id: 'counter-confetti',
    name: 'Counter Metric Confetti Sparks',
    category: 'data',
    defaultDurationInFrames: COUNTER_CONFETTI_DURATION,
    videoPreview: 'presets/videos/counter-confetti.mp4',
    recipeSource: 'data/counter-confetti.md',
    ofurryArchetype: 'B (Layered Stash)',
    intention: 'Contador numérico de alta velocidade que dispara anel de choque e faíscas neon',
    description: 'Subida acelerada de valor financeiro com travamento e partículas radiais.',
    component: CounterConfettiPreset as unknown as React.FC<Record<string, unknown>>,
  },
  {
    id: 'ring-diagram-annotation-reveal',
    name: 'Ring Diagram Annotation Reveal',
    category: 'data',
    defaultDurationInFrames: RING_DIAGRAM_ANNOTATION_REVEAL_DURATION,
    videoPreview: 'presets/videos/ring-diagram-annotation-reveal.mp4',
    recipeSource: 'data/ring-diagram-annotation-reveal.md',
    ofurryArchetype: 'A (Blueprint / Ficha)',
    intention: 'Anéis concêntricos SVG de partição de capital que deslizam e abrem anotações',
    description: 'Visualização da divisão da taxa entre banco, assessor e investidor.',
    component: RingDiagramAnnotationRevealPreset as unknown as React.FC<Record<string, unknown>>,
  },
  {
    id: 'timeline-travel',
    name: 'Timeline Travel',
    category: 'data',
    defaultDurationInFrames: TIMELINE_TRAVEL_DURATION,
    videoPreview: 'presets/videos/timeline-travel.mp4',
    recipeSource: 'data/timeline-travel.md',
    ofurryArchetype: 'A (Blueprint / Ficha)',
    intention: 'Câmera horizontal percorrendo anos de contrato com freadas em marcos críticos',
    description: 'Linha do tempo dinâmica demonstrando o desgaste do capital ano a ano.',
    component: TimelineTravelPreset as unknown as React.FC<Record<string, unknown>>,
  },
  {
    id: 'value-stagger-gradient',
    name: 'Value Stagger Gradient',
    category: 'data',
    defaultDurationInFrames: VALUE_STAGGER_GRADIENT_DURATION,
    videoPreview: 'presets/videos/value-stagger-gradient.mp4',
    recipeSource: 'ui-entrance/value-stagger-gradient.md',
    ofurryArchetype: 'B (Layered Stash)',
    intention: 'Cascata escalonada de barras demonstrando degradação e erosão de retorno',
    description: 'Sequência de barras em gradiente de alerta demonstrando a perda real.',
    component: ValueStaggerGradientPreset as unknown as React.FC<Record<string, unknown>>,
  },
  {
    id: 'beat-step-list-theme-cycle',
    name: 'Beat Step List Theme Cycle',
    category: 'effects',
    defaultDurationInFrames: BEAT_STEP_LIST_THEME_CYCLE_DURATION,
    videoPreview: 'presets/videos/beat-step-list-theme-cycle.mp4',
    recipeSource: 'rhythm/beat-step-list-theme-cycle.md',
    ofurryArchetype: 'D (Split Tensão)',
    intention: 'Avanço vertical ritmado no beat com captura em tarja neon sólida e squash pop',
    description: 'Ciclo de termos financeiros sincronizados com a batida da trilha/narração.',
    component: BeatStepListThemeCyclePreset as unknown as React.FC<Record<string, unknown>>,
  },
  {
    id: 'bezier-source-converge-merge',
    name: 'Bezier Source Converge Merge',
    category: 'effects',
    defaultDurationInFrames: BEZIER_SOURCE_CONVERGE_MERGE_DURATION,
    videoPreview: 'presets/videos/bezier-source-converge-merge.mp4',
    recipeSource: 'ui-entrance/bezier-source-converge-merge.md',
    ofurryArchetype: 'A (Blueprint / Ficha)',
    intention: 'Múltiplas fontes de dinheiro convergem por curvas neon num único ralo financeiro',
    description: 'Visualização da drenagem de capital de diferentes origens para o COE.',
    component: BezierSourceConvergeMergePreset as unknown as React.FC<Record<string, unknown>>,
  },
  {
    id: 'panel-to-canvas',
    name: 'Panel to Canvas Materialize',
    category: 'effects',
    defaultDurationInFrames: PANEL_TO_CANVAS_DURATION,
    videoPreview: 'presets/videos/panel-to-canvas.mp4',
    recipeSource: 'interaction/canvas-materialize-moves.md',
    ofurryArchetype: 'B (Layered Stash)',
    intention: 'Linha de contrato se desprende e materializa um bloco de alerta físico 2.5D',
    description: 'Destaque de uma cláusula abusiva saltando do documento para primeiro plano.',
    component: PanelToCanvasPreset as unknown as React.FC<Record<string, unknown>>,
  },
  {
    id: 'card-stack',
    name: 'Card Stack 3D Fan Out',
    category: 'effects',
    defaultDurationInFrames: CARD_STACK_DURATION,
    videoPreview: 'presets/videos/card-stack.mp4',
    recipeSource: 'ui-entrance/card-stack.md',
    ofurryArchetype: 'B (Layered Stash)',
    intention: 'Pilha de opções de ativos pop in e se abrem em leque 3D com destaque no COE',
    description: 'Comparativo físico de ativos financeiros revelando a carta perigosa.',
    component: CardStackPreset as unknown as React.FC<Record<string, unknown>>,
  },
  {
    id: 'pop-burst-confirm',
    name: 'Pop Burst Confirm',
    category: 'effects',
    defaultDurationInFrames: POP_BURST_CONFIRM_DURATION,
    videoPreview: 'presets/videos/pop-burst-confirm.mp4',
    recipeSource: 'effects/icon-performance-moves.md',
    ofurryArchetype: 'B (Layered Stash)',
    intention: 'Ícone monumental sofre compressão física e estoura com anel de choque e partículas',
    description: 'Confirmação dramática de bloqueio ou perda com AssetIcon em destaque.',
    component: PopBurstConfirmPreset as unknown as React.FC<Record<string, unknown>>,
  },
  {
    id: 'list-reveal',
    name: 'List Reveal Drift',
    category: 'effects',
    defaultDurationInFrames: LIST_REVEAL_DURATION,
    videoPreview: 'presets/videos/list-reveal.mp4',
    recipeSource: 'ui-entrance/list-reveal.md',
    ofurryArchetype: 'A (Blueprint / Ficha)',
    intention: 'Ficha técnica Blueprint com linhas surgindo em scale outBack e micro-drift contínuo',
    description: 'Apresentação de regras e condições com autoridade técnica e elegância.',
    component: ListRevealPreset as unknown as React.FC<Record<string, unknown>>,
  },
  {
    id: 'product-card-progressive-assemble',
    name: 'Product Card Progressive Assemble',
    category: 'effects',
    defaultDurationInFrames: PRODUCT_CARD_PROGRESSIVE_ASSEMBLE_DURATION,
    videoPreview: 'presets/videos/product-card-progressive-assemble.mp4',
    recipeSource: 'ui-entrance/product-card-progressive-assemble.md',
    ofurryArchetype: 'A (Blueprint / Ficha)',
    intention: 'Montagem estrutural de ficha de produto com redaction de ganho prometido e revelação do ganho real',
    description: 'Desconstrução física de uma oferta comercial na tela.',
    component: ProductCardProgressiveAssemblePreset as unknown as React.FC<Record<string, unknown>>,
  },
  {
    id: 'radial-ripple-phone-chips',
    name: 'Radial Ripple Acoustic Waves',
    category: 'effects',
    defaultDurationInFrames: RADIAL_RIPPLE_PHONE_CHIPS_DURATION,
    videoPreview: 'presets/videos/radial-ripple-phone-chips.mp4',
    recipeSource: 'effects/radial-ripple-phone-chips.md',
    ofurryArchetype: 'B (Layered Stash)',
    intention: 'Ondas acústicas e sísmicas neon concêntricas disparando tags de alerta lateral',
    description: 'Sensação de alarme financeiro irradiando do núcleo central.',
    component: RadialRipplePhoneChipsPreset as unknown as React.FC<Record<string, unknown>>,
  },
  {
    id: 'research-card-stack-scroll',
    name: 'Research Card Stack Scroll',
    category: 'effects',
    defaultDurationInFrames: RESEARCH_CARD_STACK_SCROLL_DURATION,
    videoPreview: 'presets/videos/research-card-stack-scroll.mp4',
    recipeSource: 'ui-entrance/research-card-stack-scroll.md',
    ofurryArchetype: 'A (Blueprint / Ficha)',
    intention: 'Pilha descendente de provas forenses empilhadas com profundidade de campo',
    description: 'Apresentação sucessiva de documentos e laudos que comprovam a tese.',
    component: ResearchCardStackScrollPreset as unknown as React.FC<Record<string, unknown>>,
  },
  {
    id: 'segmented-thumb-hero',
    name: 'Segmented Thumb Switch Hero',
    category: 'effects',
    defaultDurationInFrames: SEGMENTED_THUMB_HERO_DURATION,
    videoPreview: 'presets/videos/segmented-thumb-hero.mp4',
    recipeSource: 'interaction/segmented-thumb-hero.md',
    ofurryArchetype: 'D (Split Tensão)',
    intention: 'Seletor monumental alternando de Promessa para Realidade com estalo neon',
    description: 'Mudança drástica de perspectiva no momento da revelação narrativa.',
    component: SegmentedThumbHeroPreset as unknown as React.FC<Record<string, unknown>>,
  },
  {
    id: 'skeleton-reveal',
    name: 'Skeleton Reveal Wireframe',
    category: 'effects',
    defaultDurationInFrames: SKELETON_REVEAL_DURATION,
    videoPreview: 'presets/videos/skeleton-reveal.mp4',
    recipeSource: 'ui-entrance/skeleton-reveal.md',
    ofurryArchetype: 'A (Blueprint / Ficha)',
    intention: 'Ossatura técnica em linhas tracejadas que se cristaliza em evidência neon sólida',
    description: 'Construção da prova forense diante dos olhos do espectador.',
    component: SkeletonRevealPreset as unknown as React.FC<Record<string, unknown>>,
  },
  {
    id: 'svg-shape-morph',
    name: 'SVG Shape Morph',
    category: 'effects',
    defaultDurationInFrames: SVG_SHAPE_MORPH_DURATION,
    videoPreview: 'presets/videos/svg-shape-morph.mp4',
    recipeSource: 'ui-entrance/svg-shape-morph.md',
    ofurryArchetype: 'B (Layered Stash)',
    intention: 'Metamorfose orgânica contínua de contorno neon ilustrando a transmutação do risco',
    description: 'Transformação visual do conceito de Renda Fixa para Renda Variável Oculta.',
    component: SvgShapeMorphPreset as unknown as React.FC<Record<string, unknown>>,
  },
  {
    id: 'icon-flip-bloom',
    name: 'Icon Flip Bloom Outro',
    category: 'effects',
    defaultDurationInFrames: ICON_FLIP_BLOOM_DURATION,
    videoPreview: 'presets/videos/icon-flip-bloom.mp4',
    recipeSource: 'outro/ui-to-brand-morph.md',
    ofurryArchetype: 'B (Layered Stash)',
    intention: 'Ícone gira em 3D no eixo Y, atinge a lâmina zero e desabrocha no logo OFURRY com bloom',
    description: 'Fechamento de autoridade cravando a marca do canal.',
    component: IconFlipBloomPreset as unknown as React.FC<Record<string, unknown>>,
  },
  {
    id: 'bottom-push-stack-wipe',
    name: 'Bottom Push Stack Wipe',
    category: 'transition',
    defaultDurationInFrames: BOTTOM_PUSH_STACK_WIPE_DURATION,
    videoPreview: 'presets/videos/bottom-push-stack-wipe.mp4',
    recipeSource: 'transition/bottom-push-stack-wipe.md',
    ofurryArchetype: 'Cinematic Transição',
    intention: 'Nova cena empurra fisicamente a anterior de baixo para cima como cremalheira mecânica',
    description: 'Transição rígida entre blocos de narração com linha de contato neon.',
    component: BottomPushStackWipePreset as unknown as React.FC<Record<string, unknown>>,
  },
];

export const getPresetById = (id: ShotcraftPresetId): ShotcraftPresetMeta | undefined =>
  SHOTCRAFT_V1_PRESETS.find((p) => p.id === id);
